name: Lint
on: [push]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install packages
      run: npm install
    
    - name: Run ESLint
      run: ./node_modules/.bin/eslint src
