name: Lint
on: [push]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Run ESLint
      uses: stefanoeb/eslint-action@master
      with:
        node-version: ${{ matrix.node-version }}
        args: "src/**.js"
